### ISSUE TITLE
一律建議砍掉重鍊

### ISSUE THREAD

**Issue by xiaoxigua-1** [CreeperJIMM/DiscordBot-v3#2]

**Comment by CreeperJIMM** [comment]
已經有砍過一次了.....
我的程度只到這邊
不然你幫我改:(

**Comment by ChinHongTan** [comment]
西瓜太電了%%跟不上
鞭輕一點

**Comment by xiaoxigua-1** [comment]
> 西瓜太電了%%跟不上
> 
> 鞭輕一點
> 
> 
> 
> 

您

**Comment by xiaoxigua-1** [comment]
> 已經有砍過一次了.....
> 
> 我的程度只到這邊
> 
> 不然你幫我改:(

~~那基本的換行可吧~~

**Comment by xiaoxigua-1** [comment]
> > 已經有砍過一次了.....
> > 
> > 我的程度只到這邊
> > 
> > 不然你幫我改:(
> 
> ~~那基本的換行可吧~~

這樣至少能看我也能幫
不能看我想幫也不能幫
